2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Configure stats pid to 401139
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Loading settings from /users/eleves-a/2022/noam-joud-harold.ngoupeyou/.config/wandb/settings
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Loading settings from /Data/harold.ngoupeyou/cheese_classification_challenge/outputs/train/2024-05-18_14-24-20/wandb/settings
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'haroldng', 'project': 'cheese_classification_challenge', 'sweep_id': 'c2zva8pz', 'root_dir': '/Data/harold.ngoupeyou/cheese_classification_challenge', 'run_id': '0ptht4a2', 'sweep_param_path': '/Data/harold.ngoupeyou/cheese_classification_challenge/wandb/sweep-c2zva8pz/config-0ptht4a2.yaml'}
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/Data/harold.ngoupeyou/cheese_classification_challenge/train.py', 'program': '/Data/harold.ngoupeyou/cheese_classification_challenge/train.py'}
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 14:24:21,276 INFO    MainThread:401139 [wandb_init.py:_log_setup():520] Logging user logs to /Data/harold.ngoupeyou/cheese_classification_challenge/wandb/run-20240518_142421-0ptht4a2/logs/debug.log
2024-05-18 14:24:21,277 INFO    MainThread:401139 [wandb_init.py:_log_setup():521] Logging internal logs to /Data/harold.ngoupeyou/cheese_classification_challenge/wandb/run-20240518_142421-0ptht4a2/logs/debug-internal.log
2024-05-18 14:24:21,277 INFO    MainThread:401139 [wandb_init.py:init():560] calling init triggers
2024-05-18 14:24:21,277 INFO    MainThread:401139 [wandb_init.py:init():567] wandb.init called with sweep_config: {'datamodule.batch_size': 113, 'epochs': 16, 'optim.lr': 0.005340710788072082}
config: {}
2024-05-18 14:24:21,277 INFO    MainThread:401139 [wandb_init.py:init():610] starting backend
2024-05-18 14:24:21,277 INFO    MainThread:401139 [wandb_init.py:init():614] setting up manager
2024-05-18 14:24:21,291 INFO    MainThread:401139 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 14:24:21,293 INFO    MainThread:401139 [wandb_init.py:init():622] backend started and connected
2024-05-18 14:24:21,318 INFO    MainThread:401139 [wandb_run.py:_config_callback():1376] config_cb None None {'datamodule.batch_size': 113, 'epochs': 16, 'optim.lr': 0.005340710788072082}
2024-05-18 14:24:21,319 INFO    MainThread:401139 [wandb_init.py:init():711] updated telemetry
2024-05-18 14:24:21,325 INFO    MainThread:401139 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 14:24:21,827 INFO    MainThread:401139 [wandb_run.py:_on_init():2396] communicating current version
2024-05-18 14:24:21,934 INFO    MainThread:401139 [wandb_run.py:_on_init():2405] got version response 
2024-05-18 14:24:21,934 INFO    MainThread:401139 [wandb_init.py:init():795] starting run threads in backend
2024-05-18 14:24:24,638 INFO    MainThread:401139 [wandb_run.py:_console_start():2374] atexit reg
2024-05-18 14:24:24,638 INFO    MainThread:401139 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-18 14:24:24,638 INFO    MainThread:401139 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-18 14:24:24,638 INFO    MainThread:401139 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-18 14:24:24,639 INFO    MainThread:401139 [wandb_init.py:init():838] run started, returning control to user process
2024-05-18 14:24:29,898 WARNING MsgRouterThr:401139 [router.py:message_loop():77] message_loop has been closed
