2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Configure stats pid to 400473
2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Loading settings from /users/eleves-a/2022/noam-joud-harold.ngoupeyou/.config/wandb/settings
2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Loading settings from /Data/harold.ngoupeyou/cheese_classification_challenge/outputs/train/2024-05-18_14-22-12/wandb/settings
2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'haroldng', 'project': 'cheese_classification_challenge', 'sweep_id': 'c2zva8pz', 'root_dir': '/Data/harold.ngoupeyou/cheese_classification_challenge', 'run_id': 'kai1eu5g', 'sweep_param_path': '/Data/harold.ngoupeyou/cheese_classification_challenge/wandb/sweep-c2zva8pz/config-kai1eu5g.yaml'}
2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 14:22:13,116 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/Data/harold.ngoupeyou/cheese_classification_challenge/train.py', 'program': '/Data/harold.ngoupeyou/cheese_classification_challenge/train.py'}
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_init.py:_log_setup():520] Logging user logs to /Data/harold.ngoupeyou/cheese_classification_challenge/wandb/run-20240518_142213-kai1eu5g/logs/debug.log
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_init.py:_log_setup():521] Logging internal logs to /Data/harold.ngoupeyou/cheese_classification_challenge/wandb/run-20240518_142213-kai1eu5g/logs/debug-internal.log
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_init.py:init():560] calling init triggers
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_init.py:init():567] wandb.init called with sweep_config: {'datamodule.batch_size': 51, 'epochs': 18, 'optim.lr': 0.006544052078921585}
config: {}
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_init.py:init():610] starting backend
2024-05-18 14:22:13,117 INFO    MainThread:400473 [wandb_init.py:init():614] setting up manager
2024-05-18 14:22:13,142 INFO    MainThread:400473 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-18 14:22:13,143 INFO    MainThread:400473 [wandb_init.py:init():622] backend started and connected
2024-05-18 14:22:13,161 INFO    MainThread:400473 [wandb_run.py:_config_callback():1376] config_cb None None {'datamodule.batch_size': 51, 'epochs': 18, 'optim.lr': 0.006544052078921585}
2024-05-18 14:22:13,161 INFO    MainThread:400473 [wandb_init.py:init():711] updated telemetry
2024-05-18 14:22:13,164 INFO    MainThread:400473 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-18 14:22:13,523 INFO    MainThread:400473 [wandb_run.py:_on_init():2396] communicating current version
2024-05-18 14:22:13,630 INFO    MainThread:400473 [wandb_run.py:_on_init():2405] got version response 
2024-05-18 14:22:13,630 INFO    MainThread:400473 [wandb_init.py:init():795] starting run threads in backend
2024-05-18 14:22:16,386 INFO    MainThread:400473 [wandb_run.py:_console_start():2374] atexit reg
2024-05-18 14:22:16,386 INFO    MainThread:400473 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-18 14:22:16,386 INFO    MainThread:400473 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-18 14:22:16,386 INFO    MainThread:400473 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-18 14:22:16,387 INFO    MainThread:400473 [wandb_init.py:init():838] run started, returning control to user process
2024-05-18 14:22:21,824 WARNING MsgRouterThr:400473 [router.py:message_loop():77] message_loop has been closed
